version: "3"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/code
    command: >
      bash -c "python bin/init.py &&
               honcho -d . -f /Procfile start"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=clouseau
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=clouseau
    expose:
      - 5432
  redis:
    image: redis
    container_name: queue
    expose:
      - 6379
